CREATE TABLE categorias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    descricao VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP
);

CREATE TABLE produtos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    categoria_id BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
    preco NUMERIC(18, 2),
    codigo_de_barras VARCHAR(20) NOT NULL UNIQUE,
    unidade VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    perecivel BOOLEAN NOT NULL,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP
);
