-- 1. Criação da tabela estoque_lotes
CREATE TABLE estoque_lotes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
    quantidade_lote INT NOT NULL,
    validade DATE,
    codigo_de_barras VARCHAR(20) NOT NULL UNIQUE,
    data_cadastro DATE,
    data_atualizacao TIMESTAMP
);

-- 2. Criação da tabela movimentacao_estoque
CREATE TABLE movimentacao_estoque (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
    lote_id BIGINT NOT NULL REFERENCES estoque_lotes(id) ON DELETE RESTRICT,
    tipo_movimentacao VARCHAR(50) NOT NULL,
    quantidade INT NOT NULL,
    data_movimentacao TIMESTAMP,
    observacao VARCHAR(100)
);

-- 3. Alteração da tabela categorias: aumentar o tamanho da descrição
ALTER TABLE categorias
ALTER COLUMN descricao TYPE VARCHAR(100);
