-- Tabela de Permissões
CREATE TABLE permissoes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

-- Tabela de Grupos
CREATE TABLE grupos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL UNIQUE
);

-- Tabela intermediária entre Grupos e Permissões
CREATE TABLE grupo_permissoes (
    grupo_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,
    PRIMARY KEY (grupo_id, permissao_id),
    FOREIGN KEY (grupo_id) REFERENCES grupos(id) ON DELETE CASCADE,
    FOREIGN KEY (permissao_id) REFERENCES permissoes(id) ON DELETE CASCADE
);

ALTER TABLE usuarios
ADD nome VARCHAR(255);

ALTER TABLE usuarios
ADD email VARCHAR(255);

ALTER TABLE usuarios
DROP COLUMN roles;

-- Tabela intermediária entre Usuários e Grupos
CREATE TABLE usuario_grupos (
    usuario_id BIGINT NOT NULL,
    grupo_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, grupo_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (grupo_id) REFERENCES grupos(id) ON DELETE CASCADE
);

-- Inserir permissões
INSERT INTO permissoes (nome) VALUES
('PRODUTO_BUSCAR'),
('PRODUTO_DESATIVAR'),
('PRODUTO_CADASTRAR'),
('MOVIMENTACAO_CADASTRAR'),
('MOVIMENTACAO_BUSCAR'),
('MOVIMENTACAO_DELETAR'),
('ESTOQUE_BUSCAR'),
('CATEGORIA_BUSCAR'),
('CATEGORIA_CADASTRAR'),
('CATEGORIA_DESATIVAR');




